- name: Preparing Workstation
  hosts: localhost
  connection: local
  tasks:
    - name: Verify if Oh-My-zsh is installed
      command: test -d /home/{{ ansible_user_id }}/.oh-my-zsh
      register: ohmyzsh
      ignore_errors: true
    - name: Installing Oh-My-zsh
      shell:
        cmd: 'curl -fsL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | bash'
        warn: false
      when: ohmyzsh.rc != 0
    - name: Changing Default Shell to ZSH
      become: yes
      user: 
        name: '{{ ansible_user_id }}'
        shell: /bin/zsh 
    - name: Changing Default ZSH Theme to Agnoster
      lineinfile:
        path: /home/{{ ansible_user_id }}/.zshrc
        regexp: '^ZSH_THEME='
        line: 'ZSH_THEME="random"'
    - name: Creating ZSH Completion folder
      file:
        path: /home/{{ ansible_user_id }}/.oh-my-zsh/completions
        state: directory
        mode: 0755
    - name: Ading autoload to compinit
      lineinfile:
        path: /home/{{ ansible_user_id }}/.zshrc
        line: 'autoload -U compinit && compinit'
        state: present
  #  - name: copy network definition file 
  #    copy:
  #      src: ansible-net.xml
  #      dest: ~/   
  #  - name: setup kvm net 
  #    become: yes 
  #    command: virsh net-define ~/ansible-net.xml
  #  - name: start kvm net 
  #    become: yes 
  #    command: virsh net-start ansible-net
  #  - name: set autostart kvm net 
  #    become: yes 
    #  command: virsh net-autostart ansible-net
 #   - name: enable rpm fusion free
#      shell: sudo dnf install -y  https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
#
  #  - name: enable rpm fusion non-free
   #   shell: sudo dnf install -y  https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

    #- name: multimedir plugins
     # shell: sudo dnf install -y gstreamer1-plugins-{bad-\*,good-\*,base} gstreamer1-plugin-openh264 gstreamer1-libav --exclude=gstreamer1-plugins-bad-free-devel



    - name: user in groups
      become: yes
      user:
        name: jcastro
        groups: "libvirt" #, libvirt-qemu, libvirt-dnsmasq"
        state: present
    
    - name: copy conky config
      copy:
        src: ./lean-conky-config
        dest: ~/.config/conky/
        mode: 0774
    - name: running conky command
      command: ~/.config/conky/lean-conky-config/start.sh
    - name: copy bashrc file
      copy:
        src: ./.bashrc
        dest: ~/
    - name: copy zshrc
      copy:
        src: ./.zshrc
        dest: ~/
  





## to do
## configuring group in qemu.conf 
#  /etc/libvirt/qemu.conf 
##  security_driver = "none"
###  edit file /etc/systemd/resolved.conf 
## add
## DNS=192.168.122.1
## Domains=jcastro.lab

