

- name: get VM info 
  command: "ls {{ vm_location }}"
  register: disks
  changed_when: "disks.rc != 0"



- name: DHCP Old Reservation remove
  command: >
         virsh net-update {{ network }} delete  ip-dhcp-host '<host mac="'02:01:00:00:00:{{ item.value.mac }}'" ip="'192.168.122.{{ item.value.mac }}'"/>' --live --config --parent-index 0
  when: item.key not in disks.stdout
  with_dict: "{{ guests }}"
  ignore_errors: yes



- name: DHCP clean lease
  command: >
         rm -rf /var/lib/libvirt/dnsmasq/virbr0.*
  when: item.key not in disks.stdout
  with_dict: "{{ guests }}"
  ignore_errors: yes



- name: DHCP Reservation
  command: >
         virsh net-update {{ network }} add-last  ip-dhcp-host '<host mac="'02:01:00:00:00:{{ item.value.mac }}'" name="'{{ item.key }}'" ip="'192.168.122.{{ item.value.mac }}'"/>' --live --config --parent-index 0
  when: item.key not in disks.stdout
  with_dict: "{{ guests }}"


