
- name: disable swap
  shell: |
          sudo swapoff -a
          sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab   


- name: configure selinux
  shell: |
          sudo setenforce 0
          sudo sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config

- name: modprobe
  shell: |
          sudo modprobe br_netfilter
          sudo sh -c "echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables"
          sudo sh -c "echo '1' > /proc/sys/net/ipv4/ip_forward" 







- name: modprobe
  shell: |
          sudo modprobe overlay
          sudo modprobe br_netfilter

- name: set system configuration for kubernetes networking
  file:
    path: "/etc/sysctl.d/99-kubernetes-cri.conf"
    state: "touch"

- name: Add conf for containerd
  blockinfile:
    path: "/etc/sysctl.d/99-kubernetes-cri.conf"
    block: |
           net.bridge.bridge-nf-call-iptables = 1
           net.ipv4.ip_forward = 1
           net.bridge.bridge-nf-call-ip6tables = 1

- name: Apply new settings
  command: sudo sysctl --system






- name: set configuration for kubernetes repo
  file:
    path: "/etc/yum.repos.d/kubernetes.repo"
    state: "touch"

- name: Add content in repo file
  blockinfile:
    path: "/etc/yum.repos.d/kubernetes.repo"
    block: |
             [kubernetes]
             name=Kubernetes
             baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-$basearch
             enabled=1
             gpgcheck=1
             repo_gpgcheck=1
             gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
             

- name: Install kubelet kubeadm kubectl 
  command: sudo dnf install -y kubelet kubeadm kubectl 


- name: start kubelet
  systemd:
   name: kubelet
   enabled: yes
   state: started
    
- name: adicionando autocompletation
  shell:
    echo "source <(kubectl completion bash)" >> ~/.bashrc