#!/bin/bash

msg=" Eh preciso informar 1 paremetro: nome da VM "

disks="/var/lib/libvirt/images/"

[[ $# -ne 1 ]] && echo $msg && virsh list --all && exit 1

sudo virsh shutdown --domain $1
sudo virsh destroy --domain $1
sudo virsh undefine --domain $1
sudo rm -rf $disks/$1.qcow2


#add-host #2>erros_conversao.txt
if [ $? -eq 0 ]
then
  echo "VM deleta com sucesso"
  echo "____________________________"
  echo "----------------------------"

   sudo virsh list --all
else
  echo "Houve uma falha para deletar o host"
  sudo virsh list --all
fi
