---
# tasks file for kvm-provision
#- include: dhcp.yaml

- include: dhcp.yaml
  when: dhcp_reservation == 'yes'

- include: centos-install.yaml
  when: template_so == 'centos'
#
- include: ubuntu-install.yaml
  when: template_so == 'ubuntu'
#- include: inventory.yaml

- include: utils.yaml
  when: utils == 'yes'
#