   
- name: get VM disks -- Ubuntu
  command: "ls {{ vm_location }}"
  register: disks
  changed_when: "disks.rc != 0"

- name: exportando a LIBGUESTFS_BACKEND=direct
  shell: "export LIBGUESTFS_BACKEND=direct"





- name: VM Builder -- Ubuntu
  command: >
          virt-builder -v -x --format qcow2 ubuntu-18.04
          -o {{ vm_location }}{{ item.key }}.{{ file_type }}
          --size 30G
          --hostname {{ item.key }}   
          --root-password password:{{ root_pass }} 
          --run /home/jcastro/devops/kvm-provision/defaults/ubuntu-post.sh
          --ssh-inject devops:file:/home/jcastro/.ssh/id_rsa.pub
          --firstboot-command 'dhclient -v && apt install openssh-server -y'
  when: item.key not in disks.stdout
  with_dict: "{{ guests }}"
    
- name: get list of VMs  -- Ubuntu
  virt:
    command: "list_vms"
  register: vms

- name: VM Install  -- Ubuntu
  command: >
            virt-install -v --import --name {{ item.key }}
            --memory {{ item.value.mem }} --vcpus {{ item.value.cpus }}
            --disk {{ vm_location }}/{{ item.key }}.{{ file_type }}
            --noautoconsole --os-variant ubuntu18.04
            --network network={{ network }},mac=02:01:00:00:00:{{ item.value.mac }}
            --graphics vnc  
          
                
  when: item.key not in vms.list_vms and dhcp_reservation == 'yes'
  with_dict: "{{ guests }}"

- name: Register vm  -- Ubuntu
  virt:
    name: "{{ item.key }}"
    state: running
  with_dict: "{{ guests }}"

#- name: Stop VM -- Ubuntu
#  virt:
#    name: "{{ item.key }}"
#    state: shutdown 
#  with_dict: "{{ guests }}"    
#
#
#- name: Start vm  -- Ubuntu
#  virt:
#    name: "{{ item.key }}"
#    state: running
#  with_dict: "{{ guests }}"




#- name: destroy vm  -- Ubuntu
#  virt:
#    name: "{{ item.key }}"
#    command: destroy
#  with_dict: "{{ guests }}"
#  tags:
#    -  destroy

